Allow the flipped state to be passed via props
yasemincidem/Flip-Card pull request #4
Opened 2017-10-18 13:42 UTC by muyiwa-felixson

2017-10-20 14:03 UTC, calcazar requested changes
I would just chance the view back to a touchable opacity. If you wanted no opacity I would probably create a prop that controls the opacity level. Maybe even a boolean.

2017-10-20 14:03 UTC, calcazar commented on FlipCard.js
> +            <View onPress={this._flipToggleCard} style={styles.animatedContainer}>
This should remain as TouchableOpacity. React-Native doesn't officially support onPress for Views. https://facebook.github.io/react-native/docs/view.html

2017-10-23 08:34 UTC, muyiwa-felixson commented on FlipCard.js
> +            <View onPress={this._flipToggleCard} style={styles.animatedContainer}>
That works too, I would add the option to pass the opacity props to the component.

2017-10-23 08:44 UTC, muyiwa-felixson commented
@calcazar kindly review the changes

2017-10-23 12:46 UTC, calcazar requested changes
I would make the default to 0.2 and then allow users to override that with the prop

2017-10-23 12:46 UTC, calcazar commented on FlipCard.js
> +            return 1;
I would suggest we return the default of 0.2 and the let the user override the default with 1. Everything else looks good~

2017-10-23 21:06 UTC, muyiwa-felixson commented
@calcazar Note I added prop type validation

2017-11-03 20:00 UTC, calcazar approved these changes

2020-11-09 21:28 UTC, closed without merging